/**
 * Onboarding flow — shown when ~/.edgeclaw/config.yaml is missing.
 *
 * Renders a dedicated BrowserWindow loading onboarding/onboarding.html.
 * The renderer collects (providerType, baseUrl, apiKey, model) from the user
 * and POSTs it back to main via IPC. We then write a minimal *structured*
 * YAML to ~/.edgeclaw/config.yaml — claudecodeui's deep-merge will fill the
 * rest from buildDefaultEdgeClawConfig().
 *
 * The function returns:
 *   - "saved"     — user successfully completed onboarding; main should
 *                   proceed to start the server.
 *   - "cancelled" — user closed the window or hit "退出"; main should quit.
 */

import { BrowserWindow, dialog, ipcMain } from "electron";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

export type OnboardingResult = "saved" | "cancelled";

interface OnboardingPayload {
  providerType: string;
  baseUrl: string;
  apiKey: string;
  model: string;
  workspaceRoot: string;
}

const ALLOWED_PROVIDER_TYPES = new Set([
  "anthropic",
  "openai-chat",
  "openai-responses",
  "litellm",
  "ccr",
]);

/**
 * Expand ~/foo and ~ to the user's home directory. Anything that doesn't
 * start with ~ is returned unchanged. Used to normalize the workspaceRoot
 * value coming from the onboarding form before we write it to YAML and
 * before we try to mkdir it.
 */
function expandTilde(value: string): string {
  const trimmed = value.trim();
  if (trimmed === "~") return os.homedir();
  if (trimmed.startsWith("~/")) return path.join(os.homedir(), trimmed.slice(2));
  return trimmed;
}

/**
 * Validate that the chosen workspaceRoot is a usable directory:
 *   - resolves to an absolute path under the user's filesystem
 *   - parent directory exists and is writable (so mkdir can create it)
 *   - if the path itself exists, it must be a directory (not a regular
 *     file) — otherwise we'd silently scribble metadata next to it later
 *
 * Why we validate here instead of trusting whatever the user typed: a
 * typo'd or non-existent path will manifest much later as cryptic
 * "ENOENT" errors deep inside the server's project-listing code, and the
 * user has zero context to debug it.
 */
function validateAndPrepareWorkspace(rawValue: string): {
  ok: true;
  absolutePath: string;
} | { ok: false; error: string } {
  if (!rawValue.trim()) {
    return { ok: false, error: "工作目录路径不能为空" };
  }
  const absolutePath = path.resolve(expandTilde(rawValue));
  if (!path.isAbsolute(absolutePath)) {
    return { ok: false, error: `路径必须是绝对路径：${absolutePath}` };
  }
  // Refuse the home directory itself or "/" — the whole point of asking
  // for an explicit workspace is to NOT scan the entire home tree (and
  // the resulting flood of TCC prompts).
  if (absolutePath === os.homedir()) {
    return {
      ok: false,
      error:
        "不要选择整个 home 目录，会触发大量 macOS 权限弹窗。请为 EdgeClaw 单独建一个子目录。",
    };
  }
  if (absolutePath === "/" || absolutePath === path.parse(absolutePath).root) {
    return { ok: false, error: "不允许使用根目录作为 workspace。" };
  }
  try {
    if (fs.existsSync(absolutePath)) {
      const stat = fs.statSync(absolutePath);
      if (!stat.isDirectory()) {
        return {
          ok: false,
          error: `路径已存在且不是目录：${absolutePath}`,
        };
      }
    } else {
      fs.mkdirSync(absolutePath, { recursive: true });
    }
  } catch (e) {
    return {
      ok: false,
      error: `无法创建/访问目录：${
        e instanceof Error ? e.message : String(e)
      }`,
    };
  }
  return { ok: true, absolutePath };
}

function escapeYamlString(value: string): string {
  // Always quote with double-quotes and escape backslash + quote, which is
  // safe for the value subset we accept (URLs, API keys, model IDs).
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function buildConfigYaml(
  p: OnboardingPayload,
  workspaceAbsolutePath: string,
): string {
  const type = ALLOWED_PROVIDER_TYPES.has(p.providerType)
    ? p.providerType
    : "anthropic";
  return [
    "# Generated by EdgeClaw onboarding",
    "version: 1",
    "runtime:",
    `  workspacesRoot: ${escapeYamlString(workspaceAbsolutePath)}`,
    "models:",
    "  providers:",
    "    edgeclaw:",
    `      type: ${type}`,
    `      baseUrl: ${escapeYamlString(p.baseUrl)}`,
    `      apiKey: ${escapeYamlString(p.apiKey)}`,
    "  entries:",
    "    default:",
    "      provider: edgeclaw",
    `      name: ${escapeYamlString(p.model)}`,
    "agents:",
    "  main:",
    "    model: default",
    "memory:",
    "  enabled: true",
    "",
  ].join("\n");
}

function writeConfig(payload: OnboardingPayload): { ok: true } | { ok: false; error: string } {
  try {
    if (!payload || typeof payload !== "object") {
      return { ok: false, error: "Invalid payload" };
    }
    const required: Array<keyof OnboardingPayload> = [
      "providerType",
      "baseUrl",
      "apiKey",
      "model",
      "workspaceRoot",
    ];
    for (const key of required) {
      const v = payload[key];
      if (typeof v !== "string" || !v.trim()) {
        return { ok: false, error: `Missing field: ${key}` };
      }
    }

    const wsResult = validateAndPrepareWorkspace(payload.workspaceRoot);
    if (!wsResult.ok) {
      return { ok: false, error: wsResult.error };
    }

    const configDir = path.join(os.homedir(), ".edgeclaw");
    const configPath = path.join(configDir, "config.yaml");
    fs.mkdirSync(configDir, { recursive: true });
    fs.writeFileSync(
      configPath,
      buildConfigYaml(payload, wsResult.absolutePath),
      { mode: 0o600 },
    );
    return { ok: true };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}

export function showOnboardingWindow(opts: {
  preloadPath: string;
  htmlPath: string;
}): Promise<OnboardingResult> {
  return new Promise((resolve) => {
    const win = new BrowserWindow({
      width: 580,
      // Bumped from 640 → 760 to fit the new "默认工作目录" row plus its
      // multi-line hint without forcing the user to scroll.
      height: 760,
      resizable: false,
      minimizable: false,
      maximizable: false,
      fullscreenable: false,
      title: "EdgeClaw — 初始化",
      backgroundColor: "#0f1115",
      webPreferences: {
        preload: opts.preloadPath,
        contextIsolation: true,
        nodeIntegration: false,
        sandbox: true,
      },
    });

    let settled = false;
    const finish = (result: OnboardingResult) => {
      if (settled) return;
      settled = true;
      ipcMain.removeHandler("onboarding:save");
      ipcMain.removeHandler("onboarding:pickWorkspaceDir");
      ipcMain.removeAllListeners("onboarding:cancel");
      if (!win.isDestroyed()) win.close();
      resolve(result);
    };

    ipcMain.handle("onboarding:save", async (_e, payload: OnboardingPayload) => {
      const res = writeConfig(payload);
      if (res.ok) {
        // Give the renderer a tick to show its success state, then close.
        setTimeout(() => finish("saved"), 200);
      }
      return res;
    });

    // Native folder picker for the workspace-root field. We pre-fill the
    // dialog's defaultPath with whatever the user typed (after expanding
    // ~), then return the chosen absolute path back to the renderer so it
    // can update the input. Returning `null` means the user cancelled —
    // in that case the renderer keeps its current value.
    ipcMain.handle(
      "onboarding:pickWorkspaceDir",
      async (_e, currentValue: unknown): Promise<string | null> => {
        const fallback = path.join(os.homedir(), "EdgeClaw");
        let defaultPath = fallback;
        if (typeof currentValue === "string" && currentValue.trim()) {
          defaultPath = expandTilde(currentValue);
        }
        const result = await dialog.showOpenDialog(win, {
          title: "选择 EdgeClaw 默认工作目录",
          defaultPath,
          properties: ["openDirectory", "createDirectory"],
          buttonLabel: "选择此目录",
        });
        if (result.canceled || result.filePaths.length === 0) return null;
        return result.filePaths[0] ?? null;
      },
    );

    ipcMain.on("onboarding:cancel", () => finish("cancelled"));

    win.on("closed", () => finish("cancelled"));

    void win.loadFile(opts.htmlPath);
  });
}
